// Padel Market Spain — новые цифровые ниши
// Research: /02-research/spain-niches/PADEL-MARKET-SPAIN.md

const batchPadelNiches = [
  {
    name: "Padel Club Operations SaaS (Dynamic Pricing & Revenue Mgmt)",
    category: "ClubTech",
    subcategory: "SaaS",
    market: "Spain",
    description: "Platform for padel clubs: dynamic pricing engine, subscription management, occupancy analytics. No commission (vs Playtomic 5-10%). Target: €120-150/month, 700+ clubs in Spain.",
    searchVolume: 450,
    monthlySearches: 450,
    competitionLevel: "Low",
    monthlyTraffic: 2400,
    avgCPC: 1.20,
    productType: "SaaS (subscription)",
    demandScore: 9,
    supplyScore: 3,
    monetizationScore: 9,
    implementationScore: 7,
    businessModel: "Subscription €120-150/club/month, no commission",
    monthlyPotentialRevenue: 86000,
    mvpWeeks: 7,
    painPoints: [
      "Playtomic commission 5-10% = €600-900/month loss",
      "No dynamic pricing automation (static €28-32/hour)",
      "Weak tournament/league management in Playtomic Manager",
      "Zero analytics: occupancy, coach performance, churn",
      "Manual subscription tracking (no auto-renewal)"
    ],
    marketSize: "900 padel clubs in Spain",
    customerProfile: "Padel club managers, 4-8 courts",
    ltv: 5040,
    cac: 200,
    unitEconomics: "LTV/CAC 25x (36 months retention at €140/month)",
    competitorWeaknesses: {
      playtomic: "5-10% commission kills margins, weak Manager features",
      tpcMatchPoint: "Expensive, no player-side booking integration, dated UI",
      resasports: "Limited padel-specific features, poor UX"
    },
    opportunitySize: "€69k-86k/month potential (72 early adopter clubs × €120)",
    internationalPotential: "Portugal, France, Italy (secondary markets)",
    validationNotes: "Research padel clubs in Madrid, Barcelona for interviews. 40%+ initial occupancy = profitability threshold."
  },
  {
    name: "Padel Tournament SaaS (Amateur Leagues & Competitions)",
    category: "ClubTech",
    subcategory: "Tournament Management",
    market: "Spain",
    description: "Simplified tournament/league platform for clubs: round-robin, knockout, swiss. Auto-scheduling, standings, Elo rating. Integrate with payment (Bizum). Per-tournament + subscription model.",
    searchVolume: 320,
    monthlySearches: 320,
    competitionLevel: "Medium",
    monthlyTraffic: 1800,
    avgCPC: 0.85,
    productType: "SaaS (subscription + per-tournament)",
    demandScore: 8,
    supplyScore: 5,
    monetizationScore: 8,
    implementationScore: 8,
    businessModel: "€15-25/tournament OR €50-100/club/month subscription",
    monthlyPotentialRevenue: 72000,
    mvpWeeks: 6,
    painPoints: [
      "Existing platforms (Vola, Competize) too expensive (€100-300/month)",
      "Require tech skills for setup (not beginner-friendly)",
      "No payment integration with clubs (separate invoicing)",
      "No Elo/rating system built in",
      "Manual scheduling, error-prone standings"
    ],
    marketSize: "~450 clubs organize tournaments (~50% of 900), 3600 tournaments/year Spain",
    customerProfile: "Tournament organizers, club managers, league coordinators",
    ltv: 1800,
    cac: 125,
    unitEconomics: "LTV/CAC 14x (subscription €75/month or €25/tournament × 8/month)",
    competitorWeaknesses: {
      vola: "Expensive (€100-300/month), complex UI, overkill for small clubs",
      competize: "Good but not padel-focused, no payment integration",
      tournify: "Simpler but no Elo rating, weak club integration"
    },
    opportunitySize: "€12k-30k/month (200-300 clubs at mixed model)",
    internationalPotential: "Portugal, France, Central/South America",
    validationNotes: "Interview 10-15 tournament organizers. Ask: how often tournaments? spending on management today?"
  },
  {
    name: "Padel Analytics & AI Video Analysis (Club Intelligence)",
    category: "Analytics",
    subcategory: "AI Video & Performance",
    market: "Spain",
    description: "AI-powered video analysis platform: upload match video (phone), get automated stats (rally count, ball winners/losers, court position map). Club dashboard for coach performance, occupancy patterns. Mobile-first.",
    searchVolume: 280,
    monthlySearches: 280,
    competitionLevel: "Low",
    monthlyTraffic: 1600,
    avgCPC: 2.30,
    productType: "SaaS (B2B clubs + B2C players)",
    demandScore: 8,
    supplyScore: 4,
    monetizationScore: 8,
    implementationScore: 6,
    businessModel: "Club subscription €20-30/month OR per-analysis €2-5 (players)",
    monthlyPotentialRevenue: 40000,
    mvpWeeks: 11,
    painPoints: [
      "Existing analytics (SPASH, Padelytics) require 4K cameras + expensive",
      "Clubs have zero insight into coach performance metrics",
      "Players have zero feedback on technique (except coach eye)",
      "No occupancy pattern analysis (demand forecasting)",
      "No integration with club management systems"
    ],
    marketSize: "720 clubs × 2 matches/week × 50% adoption = 72k analyses/year potential",
    customerProfile: "Padel clubs (analytics), competitive players (video feedback)",
    ltv: 1080,
    cac: 250,
    unitEconomics: "LTV/CAC 4.3x (club subscription model), needs premium add-ons",
    competitorWeaknesses: {
      spashMatchAnalyzer: "Requires 4K camera + installation, €50-100/analysis (expensive)",
      padelytics: "Good AI but expensive, no club integration, not mobile-friendly",
      playsightSmartCourt: "Requires hardware investment, not scalable for small clubs"
    },
    opportunitySize: "€30k-50k/month (premium tier adoption 200+ clubs)",
    internationalPotential: "Global (AI-powered, language-agnostic)",
    validationNotes: "Test with 3-5 clubs: record matches, analyze, gather feedback. AI model needs training on padel-specific shots."
  },
  {
    name: "Padel Coaching Marketplace (Turo for Coaches)",
    category: "Marketplace",
    subcategory: "Coaching",
    market: "Spain",
    description: "Marketplace connecting independent padel coaches with students: coach profiles (experience, price, location, reviews), booking system, payment processing (Bizum). For private lessons & group classes.",
    searchVolume: 380,
    monthlySearches: 380,
    competitionLevel: "Medium",
    monthlyTraffic: 2100,
    avgCPC: 1.40,
    productType: "Marketplace (commission-based)",
    demandScore: 8,
    supplyScore: 5,
    monetizationScore: 7,
    implementationScore: 8,
    businessModel: "Commission 15-20% per lesson + Premium tier for coaches (€5-10/month)",
    monthlyPotentialRevenue: 20000,
    mvpWeeks: 7,
    painPoints: [
      "Players can't easily find independent coaches (scattered on Instagram)",
      "Coaches have no discovery mechanism (need social media presence)",
      "Payment friction (WhatsApp transfers, bank, cash)",
      "No reviews/rating system for coaches",
      "Scheduling conflicts (calendar management manual)"
    ],
    marketSize: "10-15% of 5M players want to improve = 500k-750k, 2-3% will pay = 10k-20k active students",
    customerProfile: "Amateur players (€30-50/lesson), coaches looking for students",
    ltv: 240,
    cac: 75,
    unitEconomics: "LTV/CAC 3.2x (players), but coaches pay premium (fix margin)",
    competitorWeaknesses: {
      topadel: "Positioned as camps/academies, not marketplace for casuals",
      padelglobo: "Exists but weak marketing, poor UX, not mobile-first",
      instagram: "DIY coaches, no payment processing, fragmented discovery"
    },
    opportunitySize: "€15k-25k/month (1000-2000 active students × €20/month platform spend)",
    internationalPotential: "Portugal, France, Italy, Latin America",
    validationNotes: "Interview 20 coaches + 20 players. Validate WTP for coaching, coach commission appetite."
  },
  {
    name: "Padel Equipment Subscription & Marketplace (B2B Bulk)",
    category: "E-commerce",
    subcategory: "Supply Chain / Subscription",
    market: "Spain",
    description: "Smart subscription for padel clubs: auto-replenishment of balls, racket strings, grips. Bulk discount. Analytics: consumption tracking, smart ordering recommendations. Direct club-to-distributor.",
    searchVolume: 260,
    monthlySearches: 260,
    competitionLevel: "High",
    monthlyTraffic: 1400,
    avgCPC: 1.10,
    productType: "Subscription + Marketplace",
    demandScore: 7,
    supplyScore: 7,
    monetizationScore: 8,
    implementationScore: 8,
    businessModel: "20-30% margin on bulk sales + €5-10/month subscription",
    monthlyPotentialRevenue: 50000,
    mvpWeeks: 6,
    painPoints: [
      "Clubs buy balls/strings ad-hoc (no optimization)",
      "Unknown consumption rate (how many balls/day?)",
      "No bulk discount tracking",
      "Logistics fragmented (multiple suppliers)",
      "Inventory waste (expired balls)"
    ],
    marketSize: "900 clubs × 4 courts = 3600 courts × €400/month equipment = €1.44M annual spend",
    customerProfile: "Padel club managers, facility directors",
    ltv: 3600,
    cac: 75,
    unitEconomics: "LTV/CAC 48x (36-month subscription + margin, highest potential)",
    competitorWeaknesses: {
      padelnuestro: "Dominant but no subscription, no consumption analytics",
      zonadepadel: "Traditional marketplace, no B2B focus",
      amazon: "Generic, no padel-specific bulk pricing"
    },
    opportunitySize: "€40k-60k/month (400-500 clubs × €100/month margin)",
    internationalPotential: "Portugal, France, Italy (same supply chains)",
    validationNotes: "Interview 15 clubs on consumption patterns. Partner with 2-3 brands (balls, grips) for distribution."
  }
];

module.exports = batchPadelNiches;
