// BATCH 4: Dashboard JS entries for viable niches (score ≥6.5)
// Generated: 2026-03-02
// Source: BATCH4_NAUTICAL_AGRO_HEALTH_SOLAR.md

const BATCH4_NICHES = [
  // TIER 1: GO (7.0+)
  {rank:1,name:"Dental Tourism Marketplace",sub:"Book international dental patients from UK/Germany/France",type:"HealthTech",d:8,g:8,r:8,s:8,m:8,a:7,f:5,t:4,score:7.30,mi:7,mx:8,tam:"€200M",gap:"No dedicated B2B booking for international patients; Docplanner weak",cac:200,ltv:24000,churn:"4%",y1:"€400K",y1n:25,risks:"Medical liability; international patient acquisition expensive; Docplanner expanding",gtm:"Outreach to 50 largest dental clinics (Madrid, Barcelona, Valencia); partner with medical tourism agencies; Google Ads in English/German",mvpScope:"Clinic profiles with before/after portfolio; procedure pricing packages; international patient booking; translation (EN, DE, FR); travel agency referral integration"},
  {rank:2,name:"Occupational Health SaaS (Prevención de Riesgos Laborales)",sub:"Digital PRL compliance for 1.5M Spanish companies >6 employees",type:"SaaS",d:9,g:8,r:9,s:7,m:6,a:8,f:6,t:2,score:7.40,mi:5,mx:6,tam:"€60M",gap:"No Spanish SaaS for PRL compliance; most use traditional SPA or spreadsheets",cac:100,ltv:2400,churn:"2%",y1:"€800K",y1n:20000,risks:"Low ARPU (€40/yr) requires 20K+ users; regulatory verification; traditional SPA incumbents have relationships",gtm:"Partnership with 10 HR software platforms (Factorial, BambooHR); outreach to HR consultants and business associations (CEOE, CEPYME); webinars on PRL compliance",mvpScope:"Risk assessment tool with questionnaire→risk matrix; document generator (PRL policies, risk evaluations, training plans); incident tracking; compliance checklist per Law 31/95; HR system integration (API)"},
  {rank:3,name:"Export Compliance SaaS for Smallholder Farmers",sub:"EUDR + phytosanitary + organic label compliance for 266K smallholders",type:"AgriTech",d:9,g:7,r:8,s:7,m:6,a:8,f:5,t:2,score:7.20,mi:5,mx:6,tam:"€21M",gap:"EUDR deadline Jan 2027; BatchLynx exists but weak Spain adoption; most farmers use spreadsheets",cac:80,ltv:960,churn:"15%",y1:"€100K",y1n:1250,risks:"Regulatory deadline could shift (EUDR extended before); low ARPU requires volume; farmer tech adoption slow; small business churn high (15%)",gtm:"Partner with 5-10 largest farmer cooperatives (CCAE, Ecovalia); free trial through agricultural associations (ASAJA); content marketing on EUDR compliance; webinars in Spanish/regional languages",mvpScope:"Digital record-keeping (crop, pesticide, harvest dates); EUDR compliance checklist + export doc generator; certificate management (organic, DOP); mobile app for field data; no B2B export integration initially"},
  {rank:4,name:"Farm-to-Restaurant B2B Marketplace",sub:"Direct sourcing platform connecting 380K farms to 75K+ restaurants",type:"Marketplace",d:8,g:8,r:7,s:8,m:8,a:6,f:5,t:4,score:7.10,mi:6,mx:8,tam:"€225M",gap:"Choco.com (EU-wide) exists but weak Spain focus; no Bizum integration; chef adoption low",cac:120,ltv:18000,churn:"10%",y1:"€180K",y1n:25,risks:"Logistics (cold chain, spoilage) = high operational burden; farmer supply inconsistency; Choco.com competition; delivery model unproven",gtm:"Direct outreach to 50 Michelin/high-end restaurants (personalized); farmer acquisition via regional associations (ASAJA, COAG); content on local sourcing trends; 0% commission month 1-3",mvpScope:"Farmer listing (produce, certifications, delivery zones); restaurant browsing + bulk ordering (not delivery in MVP); Bizum + SEPA invoicing; review system; WhatsApp integration for order confirmation"},

  // TIER 2: CONSIDER (6.5-6.99)
  {rank:5,name:"Wine Tourism + Enotourism Marketplace",sub:"B2B booking for 4,000+ bodegas targeting tour operators and corporates",type:"Marketplace",d:8,g:8,r:7,s:8,m:8,a:7,f:5,t:4,score:6.90,mi:7,mx:8,tam:"€600M",gap:"EnoTurismo Spain (weak); no integrated B2B booking for tour operators; FINE 2026 shows market size",cac:200,ltv:12000,churn:"7%",y1:"€240K",y1n:20,risks:"Seasonal demand (summer = 80% revenue); competition from global Viator/GetYourGuide; small bodega adoption",gtm:"Sponsor FINE 2026 (140 wineries, 100 tour ops, 50 international buyers); outreach to 30 largest bodegas (Rioja, Ribera); partner with corporate incentive travel orgs; SEO 'wine team building Spain'",mvpScope:"Bodega profile (photos, wines, experience types); date+group booking; tour operator portal for bulk/corporate bookings; rating system; Bizum integration; minimal v1"},
  {rank:6,name:"Language School B2B Marketplace (FUNDAE-integrated)",sub:"Aggregator for 5,000+ schools targeting companies with FUNDAE training budgets",type:"EdTech",d:8,g:8,r:7,s:7,m:7,a:7,f:5,t:4,score:6.90,mi:7,mx:8,tam:"€600M",gap:"No aggregator; schools fragmented; FUNDAE portal weak on booking; companies don't know eligible schools",cac:100,ltv:12000,churn:"3%",y1:"€200K",y1n:40,risks:"FUNDAE regulatory changes (subsidies could be cut); quality variance across schools; SMB awareness of FUNDAE low",gtm:"Outreach to 100 FUNDAE-registered schools; webinars through cooperative federations (COCPYME); content 'formación idiomas con subvención FUNDAE'; direct to HR managers mid-market",mvpScope:"School profiles (FUNDAE compliance, courses, instructors); corporate buyer portal (search, FUNDAE subsidy calculator); enrollment + FUNDAE paperwork generator; expense tracking; FUNDAE API integration"},
  {rank:7,name:"Marina Management SaaS",sub:"Booking + berthing + maintenance + fuel for 350+ Spanish marinas",type:"Platform",d:6,g:8,r:9,s:5,m:9,a:8,f:6,t:3,score:6.80,mi:6,mx:8,tam:"€15M",gap:"350 marinas, 95% use Excel or manual systems; no Spanish-native solution; Dockwa (US) weak",cac:800,ltv:8000,churn:"6%",y1:"€120K",y1n:3,risks:"Seasonal revenue (summer = 70% ARR); low buyer count per marina (CEO/owner); EU DG regulation could impose standards",gtm:"Direct sales to 10-15 marina chains; demo at 2026 maritime shows (FINE, nautical expos); partnership with marina associations (AMEN); white-label for booking platforms",mvpScope:"Berth management (occupancy, pricing, booking); maintenance scheduling; fuel/services invoicing; basic reporting (occupancy %, revenue)"},
  {rank:8,name:"EV Charging Home Installation Marketplace",sub:"Aggregator for 3,000+ installers connecting homeowners to Plan Auto+ subsidies",type:"Marketplace",d:8,g:7,r:5,s:7,m:8,a:7,f:4,t:4,score:6.80,mi:7,mx:8,tam:"€216M",gap:"3,000+ fragmented installers; no aggregator; slow subsidy uptake; installer quality variable",cac:150,ltv:4800,churn:"6%",y1:"€200K",y1n:40,risks:"One-time transaction (low repeat); Plan Auto+ subsidy changes (policy risk); installer safety/quality liability",gtm:"Outreach to 100 certified installers (AENOR); partnership with utilities (Endesa, Repsol); content 'cargador eléctrico casa subsidio'; paid ads 'cargador eléctrico hogar'",mvpScope:"Homeowner assessment tool (roof, grid capacity, cost estimates); installer profiles (certifications, insurance, reviews); lead distribution; subsidy/financing integration (Plan Auto+); Bizum deposits"},
  {rank:9,name:"Energy Tariff Comparator (Bizum-native)",sub:"1-click switching platform for 22.5M Spanish electricity customers",type:"FinTech",d:7,g:7,r:3,s:7,m:4,a:7,f:4,t:2,score:6.70,mi:5,mx:6,tam:"€50M",gap:"Selectra (Spain) weak on Bizum; CNMC portal government tool; no integrated switching",cac:10,ltv:50,churn:"N/A",y1:"€200K",y1n:400000,risks:"One-time transaction = low LTV; provider APIs unstable; Selectra dominance; €0.50 avg commission",gtm:"SEO 'comparador tarifas luz España'; content 'ahorrar en luz'; affiliate partnerships; Google Ads 'cambiar electricidad'",mvpScope:"Tariff comparison engine (household vs business); 1-click provider switching (API); billing calculator; savings projection; Bizum for small deposits/incentives"},
  {rank:10,name:"Pharmacy Delivery Aggregator",sub:"Prescription upload + cross-pharmacy comparison for 22,000 farmacias",type:"Marketplace",d:7,g:6,r:8,s:7,m:6,a:6,f:4,t:4,score:6.60,mi:6,mx:8,tam:"€1.1B",gap:"Mifarma/PromoFarma exist; aggregator gap is niche; no cross-pharmacy comparison for consumers",cac:100,ltv:6000,churn:"7%",y1:"€200K",y1n:50,risks:"Mifarma dominant (€150M+ revenue); prescription verification = regulatory burden; logistics = low margin",gtm:"Outreach to 100 independent farmacias (avoid direct Mifarma competition); logistics partnership (Geofresh, Cooler); marketing 'receta online rápido'; corporate wellness B2B",mvpScope:"Farmacia profiles (location, hours, services); prescription upload + pharmacist verification; medication search (cross-pharmacy); delivery coordination (3rd party logistics); Bizum + card"},
  {rank:11,name:"Event Venue Marketplace (MICE + Weddings)",sub:"B2B booking for 5,000+ fincas, bodegas, palacios",type:"Marketplace",d:7,g:6,r:7,s:7,m:7,a:6,f:5,t:4,score:6.60,mi:8,mx:10,tam:"€75M",gap:"Event Planner Spain (established but weak tech); fragmented; no dominant B2B booking platform",cac:200,ltv:9000,churn:"6%",y1:"€200K",y1n:30,risks:"Event Planner Spain competition; low-frequency bookings (7-10 venues × 1-2/yr); high CAC for B2B venue sales",gtm:"Outreach to 100 largest venues; partner with 50+ event planners (Madrid, Barcelona); sponsor IBTM World 2026 (Nov 17-19); SEO 'finca bodas Barcelona'",mvpScope:"Venue profiles (photos, capacity, amenities, pricing by type); planner + corporate buyer portal; inquiry/RFP management; booking + contract generation; Bizum deposits"},
  {rank:12,name:"Corporate Travel Management for SMBs",sub:"Booking + expense tracking + approval workflow for 750K SMBs",type:"SaaS",d:7,g:6,r:6,s:7,m:6,a:7,f:4,t:4,score:6.50,mi:7,mx:8,tam:"€30M-45M",gap:"TravelPerk (Barcelona) strong; weak Bizum integration; no Spanish HR integration; high fees for small SMBs",cac:300,ltv:4800,churn:"10%",y1:"€120K",y1n:20,risks:"TravelPerk already established (high CAC); SMB budget constraints; loyalty to Amadeus/Sabre systems",gtm:"Outreach to 50 HR consultants and staffing firms; partnership with Factorial/Workable (white-label); content 'viajes corporativos simple pymes'; direct sales (LinkedIn)",mvpScope:"Flight/hotel booking aggregation; expense tracking (receipt upload, categorization); approval workflow; Bizum/SEPA for SMB budgets; integration with Spanish HR systems"},
  {rank:13,name:"Cooperative Export SaaS",sub:"Export documentation + compliance for 2,800 agricultural cooperatives",type:"SaaS",d:7,g:6,r:8,s:5,m:6,a:7,f:6,t:3,score:6.50,mi:7,mx:8,tam:"€1.4M",gap:"No Spain-specific cooperative SaaS; manual export docs handled by lawyers; regulatory gap",cac:300,ltv:3000,churn:"3%",y1:"€75K",y1n:150,risks:"Small TAM (€1.4M); low switching costs despite regulation; lawyer incumbents have relationships",gtm:"Direct outreach to 50 largest coops (CCAE, Ecovalia); webinars through COCPYME; partner with export logistics (DHL, Geodis)",mvpScope:"Export document generator (phytosanitary, certificates, labels per target market); compliance checklist (EU vs non-EU); government portal integration (AGROALIMENTARIOS); invoicing"},

  // TIER 3: VALIDATE FIRST (6.0-6.49)
  {rank:14,name:"Telemedicine Platform (Specialist Focus)",sub:"Dermatology, nutrition, mental health specialist platform vs Doctoralia",type:"HealthTech",d:7,g:6,r:7,s:7,m:7,a:6,f:4,t:4,score:6.40,mi:8,mx:10,tam:"€400M",gap:"Doctoralia dominant; no specialist-only platform with Bizum; no corporate wellness integration",cac:150,ltv:18000,churn:"6%",y1:"€150K",y1n:20,risks:"Doctoralia dominance (expensive CAC); healthcare regulation (RGPD, e-prescription) complex; insurance reimbursement weak",gtm:"Outreach to 100 dermatologists, nutritionists, cardiologists; corporate wellness partnerships; SEO 'dermatólogo online'; referral incentives",mvpScope:"Specialist profiles (credentials, rates); video booking; Bizum + Stripe; e-prescription generation (Spanish system); patient medical history (RGPD)"},
  {rank:15,name:"Rural Tourism (Casas Rurales) Marketplace",sub:"Aggregator for 18,000 casas rurales competing with Airbnb/Booking",type:"Marketplace",d:7,g:6,r:7,s:7,m:7,a:7,f:5,t:4,score:6.40,mi:6,mx:8,tam:"€144M",gap:"Toprural (VRBO-owned) established but weak UX; Airbnb/Booking dominant; Bizum + local language gap",cac:80,ltv:6000,churn:"6%",y1:"€150K",y1n:25,risks:"Airbnb/Booking dominance (high CAC); low margins (10% take on €20K avg revenue); seasonal volatility",gtm:"Outreach to 200 independent casas rurales; SEO 'casa rural España barata'; regional tourism board partnerships; influencer travel content creators",mvpScope:"Property listing (photos, amenities, pricing, calendar); booking flow (dates, group, messaging); Bizum + card payment; review system; WhatsApp inquiry follow-up"},
  {rank:16,name:"Mental Health App (B2C, Spanish-native)",sub:"CBT app targeting 12M Spanish adults with mental health issues",type:"HealthTech",d:8,g:8,r:4,s:7,m:5,a:7,f:4,t:4,score:6.30,mi:8,mx:10,tam:"€200M-300M",gap:"BetterHelp expensive (€60-70/session); no Spanish-native CBT app; SNS waitlist 3-6 months",cac:15,ltv:360,churn:"40%",y1:"€50K",y1n:1000,risks:"App retention crisis (40% day 1 churn); mental health liability (medical oversight needed); low ARPU (€120-240/yr vs BetterHelp €720+)",gtm:"App store optimization (depresión, ansiedad, estrés keywords); YouTube channel 'salud mental simple'; corporate wellness partnerships; mental health influencers",mvpScope:"CBT workbook (guided exercises, mood tracking); therapist directory (external booking); meditation library (Spanish content); mood tracking + progress visualization; no live therapy in MVP"},
  {rank:17,name:"Boat Charter Marketplace (Spain-specific)",sub:"Charter booking platform competing with Click&Boat (28% Europe) and GetMyBoat",type:"Marketplace",d:7,g:7,r:6,s:8,m:8,a:7,f:5,t:4,score:6.20,mi:8,mx:10,tam:"€600M",gap:"Click&Boat 28% Europe share; GetMyBoat 1,800 Spain boats; weak Bizum, no local regulation features",cac:150,ltv:6000,churn:"10%",y1:"€240K",y1n:25,risks:"Click&Boat dominance; maritime law complexity (liability); seasonal demand (summer = 80% revenue)",gtm:"Direct outreach to 50+ charter companies (Balearics, Costa del Sol); 0% commission month 1-3 incentive; charter tourism packages; content SEO 'alquiler yate España'",mvpScope:"Boat listing (photos, specs, pricing); booking + calendar; WhatsApp/SMS notifications; Bizum payment; captain profile verification (nautical license)"},
  {rank:18,name:"Nautical School Aggregator Platform",sub:"Directory + booking for 500+ nautical schools (titulaciones náuticas)",type:"Directory",d:6,g:7,r:5,s:5,m:5,a:8,f:6,t:2,score:6.00,mi:5,mx:6,tam:"€3M-5M",gap:"Scattered Google + regional registries; iNautia (Europe) weak Spain; no dominant B2C marketplace",cac:200,ltv:3000,churn:"5%",y1:"€50K",y1n:5,risks:"Small TAM (€3-5M); low monetization (lead gen weak); switching costs low (free listing); regional fragmentation",gtm:"Outreach to 10-15 largest school chains; nautical association partnerships (AMEN); local PPC (Barcelona, Valencia, Málaga); corporate team-building positioning",mvpScope:"School profiles (courses, instructors, reviews); course filtering (region, level, type: vela/motor/PER); lead generation + inquiry management; review system; no marketplace—aggregator + booking orchestration"},
];

// Generate dashboard CSV for spreadsheet
function generateDashboardCSV() {
  const headers = ["Rank","Name","Sub","Type","D","G","R","S","M","A","F","T","Score","TAM","Gap","CAC","LTV","Churn","Y1 ARR","Y1 N","Risks","GTM"];
  const rows = BATCH4_NICHES.map(n => [
    n.rank,
    n.name,
    n.sub,
    n.type,
    n.d,n.g,n.r,n.s,n.m,n.a,n.f,n.t,
    n.score.toFixed(2),
    n.tam,
    n.gap.substring(0,50)+"...",
    n.cac,
    n.ltv,
    n.churn,
    n.y1,
    n.y1n,
    n.risks.substring(0,40)+"...",
    n.gtm.substring(0,40)+"..."
  ]);

  return [headers, ...rows].map(r => r.join(",")).join("\n");
}

// Quick lookup by score band
const BATCH4_BY_TIER = {
  TIER1_GO: BATCH4_NICHES.filter(n => n.score >= 7.0),
  TIER2_CONSIDER: BATCH4_NICHES.filter(n => n.score >= 6.5 && n.score < 7.0),
  TIER3_VALIDATE: BATCH4_NICHES.filter(n => n.score >= 6.0 && n.score < 6.5),
};

console.log("BATCH 4 Niches loaded:");
console.log(`Total: ${BATCH4_NICHES.length} niches`);
console.log(`TIER 1 (GO, ≥7.0): ${BATCH4_BY_TIER.TIER1_GO.length}`);
console.log(`TIER 2 (CONSIDER, 6.5-6.99): ${BATCH4_BY_TIER.TIER2_CONSIDER.length}`);
console.log(`TIER 3 (VALIDATE, 6.0-6.49): ${BATCH4_BY_TIER.TIER3_VALIDATE.length}`);

// Export
if (typeof module !== "undefined" && module.exports) {
  module.exports = { BATCH4_NICHES, BATCH4_BY_TIER, generateDashboardCSV };
}
