// BATCH 7: Spain Niches Dashboard (Logistics, Sustainability, Civic, Insurance, Remote Work)
// Generated: 2026-03-02 | Total: 28 niches | Viable (≥6.5): 16

const BATCH7_NICHES = [
  // ============ TIER 1: FAST-TRACK (Score > 7.3) ============
  {
    rank: 1,
    name: "Carbon Footprint SaaS (CSRD)",
    sub: "Automated GHG tracking + 5-yr reduction planning for 250+ employee firms",
    type: "CleanTech",
    d: 8.5, g: 8.5, r: 7.0, s: 8.0, m: 7.5, a: 7.0, f: 7.5, t: 6.5,
    score: 7.58,
    mi: 8, mx: 10,
    tam: "€9.6M",
    y1: "€1.2K-€1.6K",
    y1n: 120,
    cac: 250,
    ltv: 4300,
    churn: "15%",
    gap: "Global players €500+/mo; gap for €199-399/mo SMB solution. ~4,000 firms mandatory.",
    risks: "Regulatory interpretation risk; competitor moat weak if well-funded global player localizes",
    gtm: "ESG consultants + procurement teams; €3.75 CPC; slower B2B sales (6-12 mo)"
  },
  {
    rank: 2,
    name: "Energy Certificate (CEE) Platform",
    sub: "Automated Certificado de Eficiencia Energética issuance + management",
    type: "GovTech",
    d: 8.0, g: 8.5, r: 7.0, s: 7.5, m: 7.0, a: 6.0, f: 7.0, t: 6.5,
    score: 7.40,
    mi: 6, mx: 8,
    tam: "€24.5M",
    y1: "€800K-€1.2M",
    y1n: 900,
    cac: 220,
    ltv: 2200,
    churn: "8%",
    gap: "Market entirely manual; no SaaS platform; 500K certs/yr issued.",
    risks: "Regulatory tightening (2030=E, 2033=D) could change workflow; consultant moat",
    gtm: "Real estate networks, notary partnerships, direct B2B sales; €2.30 CPC"
  },
  {
    rank: 3,
    name: "Municipal SaaS (Ayuntamiento)",
    sub: "Modern SaaS for small towns: WhatsApp notifications, permits, waste, council minutes",
    type: "GovTech",
    d: 8.0, g: 8.5, r: 6.5, s: 8.0, m: 7.0, a: 6.5, f: 6.5, t: 7.0,
    score: 7.35,
    mi: 8, mx: 10,
    tam: "€21.4M",
    y1: "€1.2K-€1.6K",
    y1n: 1400,
    cac: 280,
    ltv: 3600,
    churn: "10%",
    gap: "8,131 municipalities, 85%+ with poor digital tools (Gestiana, SICALWIN outdated)",
    risks: "Long sales cycle (6-12 mo); municipal budgets tight; competitor Gestiona entrenched",
    gtm: "Municipal associations, España Digital 2026 partnerships; €2.00 CPC; slow gov sales"
  },
  {
    rank: 4,
    name: "Cold Chain Monitoring SaaS",
    sub: "Real-time temperature + humidity for fresh produce exporters (regulatory mandate RD 1021/2022)",
    type: "CleanTech",
    d: 8.0, g: 8.5, r: 6.5, s: 8.0, m: 7.5, a: 6.5, f: 7.0, t: 6.5,
    score: 7.35,
    mi: 8, mx: 12,
    tam: "€10.7M",
    y1: "€180K-€240K",
    y1n: 210,
    cac: 240,
    ltv: 5200,
    churn: "20%",
    gap: "30% of SME exporters lack real-time monitoring; Primafrío is carrier, not SaaS vendor",
    risks: "IoT sensor partnerships complex; regulatory compliance testing (8-12 weeks)",
    gtm: "Agricultural networks (FEPEX, PROEXPORT), slow B2B sales; €3.00 CPC"
  },
  {
    rank: 5,
    name: "WhatsApp Commerce SaaS",
    sub: "Storefront + cart + Bizum checkout for SMB sellers via WhatsApp",
    type: "RetailTech",
    d: 8.0, g: 8.0, r: 7.5, s: 7.5, m: 6.5, a: 7.0, f: 7.0, t: 7.0,
    score: 7.23,
    mi: 6, mx: 8,
    tam: "€14.9M",
    y1: "€600K-€900K",
    y1n: 750,
    cac: 150,
    ltv: 1200,
    churn: "35%",
    gap: "150K+ SMBs use WhatsApp for sales; Meta API complex; no Spain-native solution",
    risks: "WhatsApp API changes, Meta policy shifts; high churn (35%); competition from direct Meta",
    gtm: "SMB networks, retail communities, low CAC; €2.40 CPC; 70% NPS in validation"
  },

  // ============ TIER 2: DEEP DIVE (6.9-7.2) ============
  {
    rank: 6,
    name: "Parking Fine Management Platform",
    sub: "SaaS for municipalities: digital fines, notification, payment, appeals workflow",
    type: "GovTech",
    d: 7.5, g: 8.0, r: 6.5, s: 7.5, m: 7.0, a: 6.5, f: 6.0, t: 7.5,
    score: 7.15,
    mi: 6, mx: 9,
    tam: "€7.3M-€14.5M",
    y1: "€300K-€600K",
    y1n: 450,
    cac: 260,
    ltv: 3200,
    churn: "10%",
    gap: "15M fines/yr, process manual in 80%+ municipalities; low payment rates (30-40%)",
    risks: "Municipal budgets tight; slow adoption; competitor from existing ERP vendors",
    gtm: "Municipal associations, police departments; €2.00 CPC; 6-12 mo sales"
  },
  {
    rank: 7,
    name: "Cross-Border E-Commerce SaaS",
    sub: "VAT + customs duty automation for SMBs selling to France/Germany/Italy (€3 duty Jul 2026)",
    type: "FinTech",
    d: 8.5, g: 8.0, r: 6.0, s: 7.5, m: 7.0, a: 6.5, f: 6.5, t: 6.0,
    score: 7.15,
    mi: 9, mx: 12,
    tam: "€5.97M",
    y1: "€600K-€900K",
    y1n: 750,
    cac: 200,
    ltv: 3200,
    churn: "25%",
    gap: "Jul 2026 deadline urgent; 93% of e-commerce affected; no Spain-specific solution",
    risks: "Complex tax/legal compliance; long sales cycle; regulatory interpretation changes",
    gtm: "Consultancies, e-commerce networks; €2.80 CPC; slower sales (3-6 mo)"
  },
  {
    rank: 8,
    name: "Public Procurement SaaS (LCSP)",
    sub: "Bid discovery + response automation for companies bidding on Spain's public tenders",
    type: "GovTech",
    d: 7.5, g: 7.0, r: 6.0, s: 7.5, m: 6.5, a: 7.0, f: 6.0, t: 8.0,
    score: 6.95,
    mi: 8, mx: 12,
    tam: "€14.3M",
    y1: "€600K-€900K",
    y1n: 750,
    cac: 300,
    ltv: 2400,
    churn: "20%",
    gap: "10K+ tenders/yr, €60B value; SMBs lose bids due to compliance/time; JAGGAER/Zip expensive",
    risks: "Complex automation; slow B2B sales (3-6 mo); JAGGAER moat strong",
    gtm: "Industry consultants, e-procurement associations; €3.40 CPC"
  },
  {
    rank: 9,
    name: "Last-Mile Delivery SaaS",
    sub: "Unified multi-carrier dashboard for Spanish e-commerce SMBs (Correos, MRW, DHL)",
    type: "LogisticsTech",
    d: 7.5, g: 7.0, r: 6.5, s: 7.5, m: 7.0, a: 6.5, f: 6.0, t: 7.5,
    score: 6.88,
    mi: 6, mx: 8,
    tam: "€24M",
    y1: "€1.2K-€1.6K",
    y1n: 1400,
    cac: 215,
    ltv: 3200,
    churn: "35%",
    gap: "150K+ stores; ShipStation/Sendcloud underserve Spain; manual carrier switching pain",
    risks: "Sendcloud present in Spain; Correos/MRW may build own; churn high (35%)",
    gtm: "SMB networks (Cámara Comercio), WhatsApp outreach, low CAC; €1.50 CPC"
  },
  {
    rank: 10,
    name: "Seguro de Hogar Aggregator",
    sub: "Independent home insurance comparison; break Rastreator's Admiral-owned dominance",
    type: "InsurTech",
    d: 7.5, g: 7.5, r: 7.0, s: 7.0, m: 7.0, a: 6.5, f: 6.5, t: 6.5,
    score: 6.85,
    mi: 6, mx: 8,
    tam: "€1.5M",
    y1: "€200K-€400K",
    y1n: 300,
    cac: 180,
    ltv: 800,
    churn: "40%",
    gap: "50K+ searches/mo; Rastreator conflicted; gap for independent comparison",
    risks: "Rastreator entrenched; low LTV (affiliate model); high churn (40%)",
    gtm: "Google Ads, affiliate partnerships, search-driven; €2.00 CPC"
  },

  // ============ TIER 3: MONITOR (6.5-6.85) ============
  {
    rank: 11,
    name: "Returns Management Platform",
    sub: "Automated returns + refunds + restocking for e-commerce SMBs",
    type: "LogisticsTech",
    d: 7.0, g: 7.5, r: 6.5, s: 7.0, m: 6.5, a: 6.0, f: 6.5, t: 7.0,
    score: 6.80,
    mi: 6, mx: 8,
    tam: "€8M",
    y1: "€360K-€600K",
    y1n: 480,
    cac: 240,
    ltv: 2400,
    churn: "40%",
    gap: "15% return rate for 150K stores; SMBs cite reverse logistics chaos; no Spain solution",
    risks: "Transactional nature; high churn (40%); Loop Returns entering Spain",
    gtm: "Fashion/e-commerce networks, Reddit validation; €1.80 CPC"
  },
  {
    rank: 12,
    name: "Coliving Marketplace (Spain-Focused)",
    sub: "Aggregator for coliving spaces across Spain, 1-month minimum, digital nomad focus",
    type: "TravelTech",
    d: 8.0, g: 7.0, r: 7.0, s: 7.5, m: 6.5, a: 6.0, f: 7.0, t: 6.5,
    score: 6.93,
    mi: 6, mx: 8,
    tam: "€2.4M",
    y1: "€240K-€360K",
    y1n: 300,
    cac: 210,
    ltv: 1200,
    churn: "40%",
    gap: "100+ colivings scattered; Habyt/Badi not community-focused; 10K nomad visas/yr",
    risks: "Marketplace 2-sided; high churn (40%); Habyt competition strong",
    gtm: "Nomad forums, Google, direct coliving partnerships; €2.75 CPC"
  },
  {
    rank: 13,
    name: "Insurance for Autónomos",
    sub: "Bundled coverage: RC profesional + health + baja médica + contingencies for self-employed",
    type: "InsurTech",
    d: 8.0, g: 7.5, r: 6.5, s: 8.0, m: 7.5, a: 6.5, f: 7.0, t: 7.0,
    score: 7.30,
    mi: 6, mx: 9,
    tam: "€39.5M",
    y1: "€720K-€960K",
    y1n: 840,
    cac: 280,
    ltv: 2400,
    churn: "50%",
    gap: "3.3M autónomos, 60%+ buy separately; no one-stop-shop; Cobertree/Coverfy exist",
    risks: "Coverfy competitive; 50% churn (switching risk); low LTV",
    gtm: "Autónomo networks, affiliate partnerships; €2.75 CPC"
  },
  {
    rank: 14,
    name: "Solar + Battery Marketplace",
    sub: "Yelp-for-solar connecting homeowners to 3,000+ installers + financing",
    type: "CleanTech",
    d: 7.5, g: 7.0, r: 6.5, s: 7.5, m: 6.5, a: 6.0, f: 6.5, t: 7.0,
    score: 6.93,
    mi: 6, mx: 8,
    tam: "€400M+",
    y1: "€200K-€400K",
    y1n: 300,
    cac: 220,
    ltv: 2400,
    churn: "30%",
    gap: "500K+ homes interested; comparadores exist but lack reviews/financing; installer reviews sparse",
    risks: "DIY adoption rising; fragmented installer market; existing comparadores",
    gtm: "Google Ads, direct installer partnerships; €3.25 CPC"
  },
  {
    rank: 15,
    name: "Expat Health Insurance Comparison",
    sub: "Independent health insurance comparison for expats + digital nomad visa holders",
    type: "InsurTech",
    d: 8.0, g: 7.5, r: 7.0, s: 7.5, m: 6.5, a: 6.0, f: 7.0, t: 6.5,
    score: 6.88,
    mi: 5, mx: 7,
    tam: "€0.36M",
    y1: "€60K-€120K",
    y1n: 90,
    cac: 240,
    ltv: 150,
    churn: "50%",
    gap: "60K+ nomads/expats need insurance; DKV/Adeslas fragmented; nomad visa mandatory €30K",
    risks: "Regulatory mandate strong but small TAM; high churn (50%); low LTV (affiliate)",
    gtm: "Nomad + expat forums, Google, partner sites; €4.25 CPC"
  },
  {
    rank: 16,
    name: "Digital Nomad Banking/Finance SaaS",
    sub: "Banking + Bizum activation + tax guidance service for digital nomads in Spain",
    type: "FinTech",
    d: 7.5, g: 7.0, r: 7.5, s: 7.0, m: 6.5, a: 6.0, f: 7.0, t: 6.5,
    score: 6.85,
    mi: 4, mx: 6,
    tam: "€3M",
    y1: "€72K-€120K",
    y1n: 96,
    cac: 180,
    ltv: 270,
    churn: "35%",
    gap: "10K visas/yr, 80%+ need bank accounts; Wise/Revolut lack Spain-specific guidance",
    risks: "Simple product, easily replicated; low LTV; banks may add guides",
    gtm: "Nomad communities, visas.es partnerships, Google; €3.75 CPC"
  },

  // ============ NOT VIABLE (Score < 6.5) ============
  {
    rank: 17,
    name: "Community Notice Board App",
    sub: "Digital notice board + messaging for residential communities (replace paper + WhatsApp chaos)",
    type: "GovTech",
    d: 7.0, g: 7.5, r: 6.5, s: 7.0, m: 6.5, a: 6.0, f: 6.5, t: 6.5,
    score: 6.78,
    mi: 6, mx: 8,
    tam: "€14.7M",
    y1: "€180K-€360K",
    y1n: 270,
    cac: 220,
    ltv: 1200,
    churn: "25%",
    gap: "1.5M communities; WhatsApp chaos high; Nextdoor low penetration",
    risks: "2-sided marketplace friction; low ARPU (€4.99-49/yr); freemium churn",
    gtm: "Direct admin outreach, community networks; €1.50 CPC; low CAC"
  },
  {
    rank: 18,
    name: "Circular Economy Marketplace",
    sub: "B2B marketplace for industrial surplus/byproducts (scrap metals, textiles, machinery)",
    type: "CleanTech",
    d: 7.0, g: 6.5, r: 6.0, s: 7.0, m: 6.0, a: 6.5, f: 5.5, t: 7.5,
    score: 6.50,
    mi: 5, mx: 8,
    tam: "€5M",
    y1: "€150K-€300K",
    y1n: 225,
    cac: 260,
    ltv: 2400,
    churn: "35%",
    gap: "€12B waste annually; Stokarti/Cyrkl exist but not Spain-optimized",
    risks: "Offline brokers entrenched; fragmented supply; low awareness",
    gtm: "Industrial networks, CIEC partnerships; €2.00 CPC; slow B2B"
  },
  {
    rank: 19,
    name: "Loyalty Program SaaS (SMBs + Bizum)",
    sub: "Digital loyalty (stamp → points) for retail SMBs with Bizum reward redemption",
    type: "RetailTech",
    d: 7.0, g: 7.0, r: 6.5, s: 7.0, m: 6.5, a: 6.0, f: 6.5, t: 6.5,
    score: 6.70,
    mi: 5, mx: 7,
    tam: "€5.3M",
    y1: "€240K-€600K",
    y1n: 420,
    cac: 150,
    ltv: 600,
    churn: "40%",
    gap: "150K+ SMB retailers; Bizum integration unique but loyalty SaaS crowded",
    risks: "Yollty/Stamp Me competition; high churn (40%); low LTV; big chains DIY",
    gtm: "Retail networks, direct SMB outreach; €2.00 CPC; low CAC"
  },
  {
    rank: 20,
    name: "Pop-Up Retail Space Marketplace",
    sub: "Marketplace for short-term pop-up retail (1-30 days); landlords + D2C brands",
    type: "RetailTech",
    d: 7.0, g: 7.0, r: 6.5, s: 6.5, m: 6.0, a: 6.0, f: 6.0, t: 6.5,
    score: 6.50,
    mi: 5, mx: 7,
    tam: "€0.4M-€0.6M",
    y1: "€80K-€160K",
    y1n: 120,
    cac: 180,
    ltv: 300,
    churn: "50%",
    gap: "Growing trend (F1 Madrid); Storefront US-focused; limited ES inventory",
    risks: "Small TAM (€400K-600K); seasonal churn (50%); Storefront competition",
    gtm: "D2C networks, fashion brands, event organizers; €2.75 CPC"
  },
  {
    rank: 21,
    name: "Green Building Certification SaaS",
    sub: "SaaS for BREEAM/LEED certifications for Spanish commercial + residential buildings",
    type: "CleanTech",
    d: 6.5, g: 6.5, r: 6.0, s: 6.0, m: 6.0, a: 7.0, f: 5.5, t: 7.0,
    score: 6.35,
    mi: 6, mx: 8,
    tam: "€1.2M-€2.4M",
    y1: "€90K-€180K",
    y1n: 135,
    cac: 280,
    ltv: 1800,
    churn: "25%",
    gap: "EU Green Deal push; but BREEAM/LEED adoption niche; consultants offer service",
    risks: "Early-stage market; regulatory tailwind weak vs. CSRD; consultant moat",
    gtm: "Property development networks, consultants; €3.75 CPC; slow sales"
  },
  {
    rank: 22,
    name: "Embedded Insurance SaaS",
    sub: "White-label API for marketplaces to embed insurance (pet, bike, event insurance)",
    type: "InsurTech",
    d: 6.5, g: 7.0, r: 6.0, s: 6.5, m: 7.0, a: 8.0, f: 5.5, t: 9.0,
    score: 6.60,
    mi: 12, mx: 16,
    tam: "€1.2M",
    y1: "€150K-€300K",
    y1n: 225,
    cac: 400,
    ltv: 4000,
    churn: "25%",
    gap: "Emerging use case in Spain; Qover expensive (€50K+); gap for SMB-friendly",
    risks: "Complex tech, insurance expertise required; long timeline (12-16 weeks); small TAM",
    gtm: "Marketplace networks, B2B sales; €4.25 CPC; slow"
  },
  {
    rank: 23,
    name: "Digital Broker Platform (Corredor SaaS)",
    sub: "Modern SaaS for independent insurance brokers: client mgmt, quotes, renewals",
    type: "InsurTech",
    d: 7.5, g: 7.5, r: 6.5, s: 7.0, m: 6.5, a: 6.5, f: 6.5, t: 7.0,
    score: 6.95,
    mi: 6, mx: 9,
    tam: "€17.9M",
    y1: "€600K-€1.2K",
    y1n: 900,
    cac: 250,
    ltv: 1800,
    churn: "20%",
    gap: "5,000 brokers, 90%+ manual; low margins (3-8% commission) pressure adoption",
    risks: "Broker inertia; low margins; slow sales cycle",
    gtm: "Broker associations (COLEGIO DE CORREDORES); €2.75 CPC; 6-12 mo sales"
  },
  {
    rank: 24,
    name: "Seguro de Salud Aggregator",
    sub: "Independent private health insurance comparison; break Adeslas/Sanitas/Mapfre oligopoly",
    type: "InsurTech",
    d: 7.5, g: 7.5, r: 6.5, s: 7.0, m: 6.5, a: 6.5, f: 6.0, t: 6.5,
    score: 6.80,
    mi: 6, mx: 8,
    tam: "€1.4M",
    y1: "€150K-€300K",
    y1n: 225,
    cac: 200,
    ltv: 600,
    churn: "60%",
    gap: "11.5M private holders; oligopoly (3 players); no independent comparison",
    risks: "High churn (60%); oligopoly pricing power strong; low LTV",
    gtm: "Google Ads, affiliate partnerships, search-driven; €3.25 CPC"
  },
  {
    rank: 25,
    name: "Remote Work Certification SaaS",
    sub: "Compliance SaaS for Spanish companies: Ley de Trabajo a Distancia remote agreements",
    type: "GovTech",
    d: 6.5, g: 6.5, r: 6.0, s: 7.0, m: 6.5, a: 6.0, f: 5.5, t: 6.5,
    score: 6.35,
    mi: 4, mx: 6,
    tam: "€8.9M",
    y1: "€90K-€180K",
    y1n: 135,
    cac: 200,
    ltv: 50,
    churn: "50%",
    gap: "Regulatory but low enforcement; SMBs use free templates or lawyers",
    risks: "Low urgency post-COVID; free alternatives abundant; low LTV",
    gtm: "HR consultants, LinkedIn; €2.30 CPC; slow B2B"
  },
  {
    rank: 26,
    name: "NIE/TIE Appointment Bot",
    sub: "Service to monitor + book NIE/TIE appointments (automate manual page refresh)",
    type: "GovTech",
    d: 8.5, g: 8.0, r: 6.5, s: 7.5, m: 6.5, a: 7.5, f: 6.0, t: 6.5,
    score: 6.70,
    mi: 4, mx: 6,
    tam: "€1.47M",
    y1: "€150K-€300K",
    y1n: 225,
    cac: 180,
    ltv: 50,
    churn: "60%",
    gap: "60K+ expats need NIE; manual refresh = desperation; legal gray area (ToS)",
    risks: "LEGAL RISK (bot ToS violation); regulatory risk; reputational damage; 60% churn",
    gtm: "Expat forums, visa sites; €5.00 CPC; risky"
  }
];

// Dashboard Summary
const SUMMARY = {
  total: 28,
  viable: 16,
  tier1: 5,
  tier2: 4,
  tier3: 7,
  notViable: 6,

  topByTam: [
    { name: "Municipal SaaS", tam: "€21.4M", score: 7.35 },
    { name: "Energy Certificate", tam: "€24.5M", score: 7.40 },
    { name: "Last-Mile Delivery", tam: "€24M", score: 6.88 },
    { name: "Insurance for Autónomos", tam: "€39.5M", score: 7.30 }
  ],

  topByScore: [
    { name: "Carbon Footprint CSRD", score: 7.58, tam: "€9.6M" },
    { name: "Energy Certificate", score: 7.40, tam: "€24.5M" },
    { name: "Municipal SaaS", score: 7.35, tam: "€21.4M" },
    { name: "Cold Chain Monitoring", score: 7.35, tam: "€10.7M" },
    { name: "Insurance for Autónomos", score: 7.30, tam: "€39.5M" }
  ],

  fastestMvp: [
    { name: "Digital Nomad Banking", weeks: "4-6", score: 6.85 },
    { name: "Remote Work Certification", weeks: "4-6", score: 6.35 },
    { name: "Loyalty Program SaaS", weeks: "5-7", score: 6.70 },
    { name: "Community Notice Board", weeks: "6-8", score: 6.78 }
  ],

  highestLtv: [
    { name: "Cold Chain Monitoring", ltv: 5200, score: 7.35 },
    { name: "Municipal SaaS", ltv: 3600, score: 7.35 },
    { name: "Last-Mile Delivery", ltv: 3200, score: 6.88 },
    { name: "Parking Fine Management", ltv: 3200, score: 7.15 }
  ]
};

// Export
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { BATCH7_NICHES, SUMMARY };
}

console.log("BATCH 7 Dashboard loaded: 28 niches, 16 viable (≥6.5)");
console.log("Top 3 Fast-Track (Tier 1):");
console.log("  1. Carbon Footprint CSRD (7.58) — €9.6M TAM");
console.log("  2. Energy Certificate (7.40) — €24.5M TAM");
console.log("  3. Municipal SaaS (7.35) — €21.4M TAM");
