// TOP 5 MISSING NICHES DASHBOARD ENTRIES
// Generated: 2026-03-02
// Use these entries to populate niche scoring dashboard

const top5MissingNiches = [
  {
    rank: 1,
    name: "Comunidades de Vecinos SaaS",
    sub: "Digital junta convocation + derrama tracking for Spain's 490K residential communities",
    type: "Vertical",
    d: 8,
    g: 9,
    r: 8,
    s: 9,
    m: 7,
    a: 8,
    f: 7,
    t: 8,
    score: 8.1,
    mi: 5,
    mx: 6,
    tam: "€117.6M",
    gap: "Zero digital-native competitor. 9.8M apartments managed via paper & WhatsApp. Need: junta convocation, presupuestos, derrama, maintenance requests, insurance tracking.",
    cac: 10,
    ltv: 240,
    churn: 2,
    y1: 45000,
    y1n: 180,
    risks: "Gesfincas/Urbanarque modernization, WhatsApp entrenchment, regulatory fragmentation across regions",
    gtm: "Colegio Profesional de Administradores de Fincas partnership + free trial junta convocation + property manager association outreach",
    mvpScope: "Junta convocation templating, presupuesto forms, online vote tracking, derrama calculator, member directory"
  },
  {
    rank: 2,
    name: "Payroll SaaS for Spanish SMBs",
    sub: "Modern nómina engine (14 payments, SS, AEAT, ERTE) replacing outdated A3 Nómina",
    type: "HRTech",
    d: 8,
    g: 8,
    r: 8,
    s: 9,
    m: 6,
    a: 6,
    f: 8,
    t: 8,
    score: 7.9,
    mi: 8,
    mx: 10,
    tam: "€1.03B",
    gap: "No modern SaaS replacement for legacy A3 Nómina. Complex payroll (14 monthly payments, Seguridad Social tiers, ERTE eligibility, regional rules). Market gap at €30-80/mo.",
    cac: 15,
    ltv: 720,
    churn: 3,
    y1: 120000,
    y1n: 2000,
    risks: "Factorial adds payroll module, AEAT/SS API restrictions, gestoría distribution conflict, sales cycle length",
    gtm: "Accounting firm white-label (20% revenue share) + CPA certification partnerships + webinars on 2026 SS changes (€1K test spend)",
    mvpScope: "Nómina calculation (14-payment schedule), AEAT 152/160 generation, Seguridad Social management, single-doc approval"
  },
  {
    rank: 3,
    name: "Gestoría Software — Modern SaaS",
    sub: "Replace A3/Sage for 30K gestores: multi-client account, tax files, nómina, VeriFactu, compliance",
    type: "FinTech",
    d: 7,
    g: 8,
    r: 7,
    s: 8,
    m: 8,
    a: 7,
    f: 8,
    t: 8,
    score: 7.6,
    mi: 5,
    mx: 6,
    tam: "€72M",
    gap: "30K gestorías use 20-year-old software (A3, Sage). Zero modern gestoría-specific SaaS. Market gap: €199-499/mo for cloud platform with client portfolio management.",
    cac: 125,
    ltv: 2400,
    churn: 2,
    y1: 85000,
    y1n: 680,
    risks: "A3/Sage rapid modernization, cloud adoption resistance (data privacy), VeriFactu API volatility",
    gtm: "Colegio Profesional de Gestores partnership + VeriFactu compliance webinars + free migration service from legacy software",
    mvpScope: "Multi-client account management, tax file generation, nómina + SS/AEAT, VeriFactu integration, client portal, compliance checklist"
  },
  {
    rank: 4,
    name: "Expense Management SaaS + VeriFactu",
    sub: "Receipt-to-AEAT filing for 3.2M Spanish SMBs. Factura + Seguridad Social integration.",
    type: "FinTech",
    d: 7,
    g: 7,
    r: 7,
    s: 8,
    m: 7,
    a: 7,
    f: 7,
    t: 8,
    score: 7.3,
    mi: 5,
    mx: 6,
    tam: "€368M",
    gap: "Spendesk/Pleo are UK-centric. No Spanish SaaS with automated receipt→Factura→AEAT pipeline. Critical gap: VeriFactu integration deadline Jan 2027.",
    cac: 26,
    ltv: 960,
    churn: 4,
    y1: 95000,
    y1n: 1600,
    risks: "Spendesk/Pleo market entry, AEAT API changes, accounting firm distribution conflict",
    gtm: "Accounting firms as channel (revenue share model) + LinkedIn CFO outreach (50-300 employee segment) + VeriFactu compliance webinars (3/week)",
    mvpScope: "Receipt scanning + OCR, Factura generation, AEAT CSV export, 2-3 payment integrations (Stripe, Bizum), basic approval workflow"
  },
  {
    rank: 5,
    name: "FUNDAE Corporate Training SaaS",
    sub: "Track €200-600/employee/year training credits. Fix €735M annual waste from underutilization.",
    type: "HRTech",
    d: 7,
    g: 8,
    r: 6,
    s: 9,
    m: 8,
    a: 7,
    f: 6,
    t: 7,
    score: 7.3,
    mi: 4,
    mx: 5,
    tam: "€10.08M",
    gap: "Zero SaaS to manage FUNDAE bonification budgets. 35% of €2.1B budget wasted annually. Market gap: €29-99/mo platform with course recommender + ROI tracking.",
    cac: 32,
    ltv: 480,
    churn: 4,
    y1: 65000,
    y1n: 1100,
    risks: "FUNDAE portal direct improvements, accounting firm entry, complex Bonificaciones rule changes",
    gtm: "Accounting firm white-label (20% share) + CFO/HR LinkedIn targeting + FUNDAE awareness webinars + Bonificaciones success stories",
    mvpScope: "Budget tracker (annual FUNDAE allocation), course recommender, bonification request helper, ROI calculator, compliance documentation"
  }
];

// Export for dashboard
export { top5MissingNiches };
